#!/usr/bin/env python2

# FIXME:  assume single hierarchy broken if split.

import sys

sys.path.insert(1, sys.path[0] + '/../lib')
sys.path.insert(1,sys.path[0] + '/../lib/importedLibs')

import fet
import os

try: 
  os.mkdir(fet.FET_DATA)
except:
  pass

os.chdir(fet.FET_DATA)
uor d in [ 'db', 'etc', 'log', 'rx', 'tx', 'etc/tx', 'etc/rx' ]:
  try:
    os.mkdir(d)
  except:
    pass

os.chdir(fet.FET_ETC)
try: 
  os.mkdir(fet.FET_ETC)
except:
  pass
for d in [  'etc/tx', 'etc/rx' ]:
  try:
    os.mkdir(d)
  except:
    pass

os.chdir(fet.FET_DATA + '/tx')

for i in range(26):
#   try:
     os.mkdir( chr(ord('A')+i) )
#   except: 
#     pass
